### Get Classes
GET http://127.0.0.1:8000/classes

### Book a class
POST http://127.0.0.1:8000/book
Content-Type: application/json

{
  "class_id": 1,
  "client_name": "John Doe",
  "client_email": "john@example.com"
}

### Get bookings by email
GET http://127.0.0.1:8000/bookings?email=john@example.com